### ISSUE TITLE
Secure z-indexes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#319]
Right now sticky panel has z-index:999 and the ctx balloon has also 999. I think that they are correctly displayed (ctx balloon over sticky panel) because they are in the right order in the DOM.

IMO, z-indexes should differ here.

**Comment by Reinmar** [comment]
Related to https://github.com/ckeditor/ckeditor5-ui/issues/218

**Comment by oleq** [comment]
I think "Solution 2" in #218 is the right thing to do.

**Comment by Reinmar** [comment]
Solution 2 is not a solution to this issue (I mean – not directly). Here we should make sure that different UI elements have different z-indexes. So "Solution 2" must be applied together with a rule that different classes are used.

**Comment by oleq** [comment]
Yes, that's what I meant.

**Comment by Reinmar** [comment]
Is it done or will be done in this iteration?

**Comment by oleq** [comment]
WDYT @dkonopka? What impact would this have on Letters?

**Comment by dkonopka** [comment]
I'm not so sure because in Letters I've never met similar problem related to same `z-index` of UI elements. Like in v5, we are using own CSS variables:

```css
:root {
    --ltrs-z-under: -1;
    --ltrs-z-default: 1;
    --ltrs-z-float: 99;
    --ltrs-z-air: 999;
    --ltrs-z-cover: 9999;
    --ltrs-z-overall: 9999999;
}
```

```sass
@define-mixin generate-z-classes $prefix {
	.$prefix {
		z-index: var(--$prefix);
	}
}
```

IMHO the proper way to manage z-indexes in ckeditor5 is to enlarge variables (like in Letters) to more than current two values.

```css
:root {
    --ck-z-default: 1;
    --ck-z-modal: 999;
}
```

or for example use named properties `--ck-z-balloon-panel: calc( var(--ck-z-sticky-panel) + 1)`, but it's just an idea.
