### ISSUE TITLE
Remove the legacy BoxedEditor#width/height

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui#320]
They are there from the day one. We never used them. They have no effect on the editor but may be confusing if someone checks how to set the editor height.

**Comment by oleq** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5-ui/issues/25.

**Comment by Reinmar** [comment]
PS. If you're looking for how to set CKEditor 5's height and width, then the news is that:

* There's no `config.height` and `config.width` like in CKEditor 4.
* You can just use CSS.

To set the height:

```css
.ck-editor__editable {
    min-height: 400px;

    /* or: */
    height: 400px;
}
```

To set the width:

```cs
.ck-editor {
    width: 400px;
}
```
